version: 2.1
orbs:
  node: 'cimg/node:18.14.1'

jobs:
  # build: TODO
  lint:
    docker:
      - image: cimg/node:18.15
    steps:
      - checkout
      - node/install
      - run:
          name: ESLint
          command: yarn lint:eslint
      - run:
          name: Prettier
          command: yarn prettier:check
  typecheck:
    docker:
      - image: cimg/node:18.15
    steps:
      - checkout
      - node/install
      - run:
          name: Typecheck (tsc)
          command: yarn tsc
      - run:
          name: Typecheck (flow)
          command: yarn flow check

workflows:
  version: 2
  all_workflow:
    jobs:
      - lint
      - typecheck
      - node/test
