version: 2
jobs:
  unit_tests:
    working_directory: ~/StreakYC/GmailSDK
    parallelism: 1
    docker:
      - image: cimg/node:18.14-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dep-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v3-dep-{{ .Branch }}-
            - v3-dep-master-
            - v3-dep-
      - run: yarn
      - save_cache:
          key: v3-dep-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.yarn/bin/
            - ~/.config/yarn/global/
            - ~/.cache
      - run:
          name: Lint and Typecheck
          command: yarn test
      - run:
          name: Unit Tests
          command: yarn jest --detectOpenHandles

workflows:
  version: 2
  all_workflow:
    jobs:
      - unit_tests
