version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  sdk:
    docker:
      - image: cimg/node:18.15.0

jobs:
  build:
    executor: sdk
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Build '@inboxsdk/core' version
          command: yarn gulp
      - run:
          name: Check output files exist
          command: ls packages/core/inboxsdk.js
      - run:
          name: Clean
          command: yarn gulp clean
  lint:
    executor: sdk
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: ESLint
          command: yarn lint:eslint
      - run:
          name: Prettier
          command: yarn prettier:check
  test:
    executor: sdk
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          # https://stackoverflow.com/questions/71985308/jest-a-worker-process-has-failed-to-exit-gracefully-and-has-been-force-exited#comment130902392_74087365
          command: yarn test --detectOpenHandles
          name: Tests
  typecheck:
    executor: sdk
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Typecheck (tsc)
          command: yarn tsc
      - run:
          name: Typecheck (flow)
          command: yarn flow check

workflows:
  version: 2
  all_workflow:
    jobs:
      - build
      - lint
      - test
      - typecheck
