version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  sdk:
    docker:
      - image: cimg/node:18.15.0

jobs:
  # build: TODO
  lint:
    executor: sdk
    steps:
      - checkout
      - node/install
      - node/install-packages:
          pkg-manager: yarn-berry
          check-cache: always
      - run:
          name: ESLint
          command: yarn lint:eslint
      - run:
          name: Prettier
          command: yarn prettier:check
  test:
    executor: sdk
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
          check-cache: always
      - run:
          command: yarn test
          name: Tests
  typecheck:
    executor: sdk
    steps:
      - checkout
      - node/install
      - node/install-packages:
          pkg-manager: yarn-berry
          check-cache: always
      - run:
          name: Typecheck (tsc)
          command: yarn tsc
      - run:
          name: Typecheck (flow)
          command: yarn flow check

workflows:
  version: 2
  all_workflow:
    jobs:
      - lint
      - test
      - typecheck
